const products=[
 {id:'hf204',code:'HF204',ean:'824225110150',name:'Olejový filter HIFLOFILTRO HF204',brand:'HIFLOFILTRO',category:'filtre',vehicle:'Yamaha',model:'Grizzly 700',year:'2016–2025',price:11.9,stock:12,sale:false},
 {id:'hf303',code:'HF303',ean:'824225110181',name:'Olejový filter HIFLOFILTRO HF303',brand:'HIFLOFILTRO',category:'filtre',vehicle:'Honda',model:'CBR 600',year:'2001–2006',price:10.4,stock:7,sale:true},
 {id:'brm01',code:'BRM-01',ean:'5900000000011',name:'Brzdové doštičky Brembo – predné',brand:'Brembo',category:'brzdy',vehicle:'Yamaha',model:'Grizzly 700',year:'2016–2025',price:34.9,stock:5,sale:false},
 {id:'mitas-atv',code:'ATV-25X8',ean:'8590341000012',name:'ATV pneumatika Mitas 25 × 8 R12',brand:'Mitas',category:'pneumatiky',vehicle:'CFMOTO',model:'CFORCE 520',year:'2019–2025',price:94.5,stock:0,sale:false},
 {id:'chain-520',code:'DID-520VX3',ean:'4525516330013',name:'Reťazová sada D.I.D 520VX3',brand:'D.I.D',category:'pohon',vehicle:'Honda',model:'CBR 600',year:'2001–2006',price:129,stock:3,sale:true},
 {id:'air-yam',code:'HFA4912',ean:'824225120357',name:'Vzduchový filter HIFLOFILTRO HFA4912',brand:'HIFLOFILTRO',category:'filtre',vehicle:'Yamaha',model:'Grizzly 700',year:'2016–2025',price:27.8,stock:9,sale:false}
];
const state={cart:JSON.parse(localStorage.getItem('amdpro-cart')||'[]'),query:'',category:'',brand:'',vehicle:JSON.parse(localStorage.getItem('amdpro-vehicle')||'null')};
const main=document.querySelector('#main'),money=n=>new Intl.NumberFormat('sk-SK',{style:'currency',currency:'EUR'}).format(n);
function save(){localStorage.setItem('amdpro-cart',JSON.stringify(state.cart));renderCartCount()}
function esc(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function matches(p,q){const text=Object.values(p).join(' ').toLocaleLowerCase('sk');return q.trim().toLocaleLowerCase('sk').split(/\s+/).every(x=>text.includes(x.normalize('NFD').replace(/\p{Diacritic}/gu,''))||text.normalize('NFD').replace(/\p{Diacritic}/gu,'').includes(x.normalize('NFD').replace(/\p{Diacritic}/gu,'')))}
function card(p){return `<article class="card"><div class="product-art" role="img" aria-label="${esc(p.name)}">${esc(p.brand.slice(0,3))}</div><div class="card-body"><span class="code">Kód: ${esc(p.code)}</span><h3><a href="#/product/${p.id}">${esc(p.name)}</a></h3><span class="stock ${p.stock?'':'out'}">${p.stock?`Skladom ${p.stock} ks`:'Momentálne nedostupné'}</span><div class="price">${money(p.price)}</div><div class="card-actions"><a href="#/product/${p.id}">Detail</a><button type="button" data-add="${p.id}" ${p.stock?'':'disabled aria-disabled="true"'}>${p.stock?'Pridať do košíka':'Nedostupné'}</button></div></div></article>`}
function home(){main.innerHTML=`<section class="hero"><div><div class="eyebrow">Diely pre motocykle a štvorkolky</div><h1>Nájdite diel, ktorý naozaj pasuje.</h1><p>Vyhľadávajte podľa názvu, produktového kódu, EAN, značky alebo modelu vozidla.</p></div><form id="finder" class="finder"><h2>Vyberte svoje vozidlo</h2><div class="finder-grid"><label>Typ<select name="type"><option>Motocykel</option><option>Štvorkolka</option></select></label><label>Značka<select name="brand"><option value="">Vyberte</option><option>Yamaha</option><option>Honda</option><option>CFMOTO</option></select></label><label>Model<select name="model"><option value="">Všetky modely</option><option>Grizzly 700</option><option>CBR 600</option><option>CFORCE 520</option></select></label><label>Rok<select name="year"><option value="">Všetky roky</option><option>2025</option><option>2024</option><option>2023</option></select></label><button class="primary" type="submit">Zobraziť kompatibilné diely</button></div></form></section><section class="section"><div class="section-head"><div><span class="eyebrow">Odporúčané</span><h2>Najžiadanejšie diely</h2></div></div><div class="products">${products.slice(0,4).map(card).join('')}</div></section>`;document.querySelector('#finder').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.vehicle={brand:f.get('brand'),model:f.get('model'),year:f.get('year')};localStorage.setItem('amdpro-vehicle',JSON.stringify(state.vehicle));location.hash='#/search?vehicle=1'})}
function listing(opts={}){let list=products.filter(p=>(!opts.sale||p.sale)&&(!opts.category||p.category===opts.category)&&(!state.query||matches(p,state.query))&&(!state.brand||p.brand===state.brand));if(state.vehicle?.brand)list=list.filter(p=>p.vehicle===state.vehicle.brand&&(!state.vehicle.model||p.model===state.vehicle.model));main.innerHTML=`<section class="section"><div class="section-head"><div><span class="eyebrow">Katalóg</span><h1>${opts.title||'Výsledky vyhľadávania'}</h1></div><strong>${list.length} produktov</strong></div>${state.query?`<p>Výsledky pre: <strong>„${esc(state.query)}“</strong></p>`:''}<div class="toolbar"><label class="sr-only" for="brand-filter">Značka</label><select id="brand-filter"><option value="">Všetky značky</option>${[...new Set(products.map(p=>p.brand))].map(x=>`<option ${state.brand===x?'selected':''}>${x}</option>`).join('')}</select><label class="sr-only" for="sort">Radenie</label><select id="sort"><option value="recommended">Odporúčané</option><option value="low">Najlacnejšie</option><option value="high">Najdrahšie</option><option value="az">Názov A–Z</option></select></div>${list.length?`<div id="product-list" class="products">${list.map(card).join('')}</div>`:`<div class="empty"><h2>Nenašli sme žiadne produkty</h2><p>Skontrolujte výraz, skúste produktový kód alebo nám napíšte na <a href="mailto:info@amdpro.eu">info@amdpro.eu</a>.</p><a href="#/">Späť na hlavnú stránku</a></div>`}</section>`;document.querySelector('#brand-filter').onchange=e=>{state.brand=e.target.value;listing(opts)};document.querySelector('#sort').onchange=e=>{const mode=e.target.value,grid=document.querySelector('#product-list');if(!grid)return;list.sort((a,b)=>mode==='low'?a.price-b.price:mode==='high'?b.price-a.price:mode==='az'?a.name.localeCompare(b.name,'sk'):products.indexOf(a)-products.indexOf(b));grid.innerHTML=list.map(card).join('')}}
function detail(id){const p=products.find(x=>x.id===id);if(!p)return notFound();main.innerHTML=`<section class="section detail"><div class="product-art" role="img" aria-label="${esc(p.name)}">${esc(p.brand)}</div><div><span class="eyebrow">${esc(p.category)}</span><h1>${esc(p.name)}</h1><p class="code">Produktový kód: ${esc(p.code)}</p><p class="stock ${p.stock?'':'out'}">${p.stock?'Skladom – odosielame do 24 hodín':'Momentálne nedostupné'}</p><div class="price">${money(p.price)}</div><button class="primary" data-add="${p.id}" ${p.stock?'':'disabled aria-disabled="true"'}>${p.stock?'Pridať do košíka':'Momentálne nedostupné'}</button><h2>Kompatibilita</h2><p><strong>${esc(p.vehicle)} ${esc(p.model)}</strong>, ročníky ${esc(p.year)}.</p><a href="mailto:info@amdpro.eu?subject=${encodeURIComponent('Overenie kompatibility '+p.code)}&body=${encodeURIComponent(p.name+'\n'+location.href)}">Overiť kompatibilitu dielu</a><h2>Technické údaje</h2><table><tr><th>Výrobca</th><td>${esc(p.brand)}</td></tr><tr><th>Kód</th><td>${esc(p.code)}</td></tr><tr><th>EAN</th><td>${esc(p.ean)}</td></tr></table></div></section>`}
function howTo(){main.innerHTML=`<article class="section prose"><h1>Ako nakupovať</h1><h2>1. Ako nájsť správny diel</h2><p>Použite vyhľadávanie podľa názvu, kódu, OEM čísla, značky alebo modelu vozidla. Pomôže aj konfigurátor na úvodnej stránke.</p><h2>2. Ako overiť kompatibilitu</h2><p>Na detaile skontrolujte model a ročník. Ak si nie ste istí, kliknite na „Overiť kompatibilitu dielu“.</p><h2>3. Vloženie do košíka</h2><p>Skladový produkt pridáte tlačidlom „Pridať do košíka“. Nedostupný produkt sa objednať nedá.</p><h2>4. Doprava a platba</h2><p>V košíku pokračujte k objednávke, vyberte dopravu a spôsob platby a skontrolujte celkovú cenu.</p><h2>5. Dokončenie objednávky</h2><p>Vyplňte meno a e-mail. Po úspešnom odoslaní sa zobrazí potvrdenie.</p><h2>6. Odoslanie a osobný odber</h2><p>Skladový tovar zvyčajne odosielame do 24 hodín. O pripravenom osobnom odbere vás budeme informovať.</p><h2>7. Zmena, vrátenie a reklamácia</h2><p>Čo najskôr nás kontaktujte na <a href="tel:+421000000000">+421 000 000 000</a> alebo <a href="mailto:info@amdpro.eu">info@amdpro.eu</a>. Podrobnosti nájdete v <a href="#/terms">obchodných podmienkach</a>.</p></article>`}
function brands(){main.innerHTML=`<section class="section"><h1>Značky</h1><p>Výrobcovia zoradení abecedne.</p><div class="products">${[...new Set(products.map(p=>p.brand))].sort().map(b=>`<a class="card card-body" href="#/search?brand=${encodeURIComponent(b)}"><h2>${esc(b)}</h2><span>Zobraziť produkty</span></a>`).join('')}</div></section>`}
function legal(type){main.innerHTML=`<article class="section prose"><h1>${type==='privacy'?'Ochrana osobných údajov':'Obchodné podmienky'}</h1><p>Táto stránka je pripravená ako technický náhľad. Pred zverejnením musí byť doplnený a schválený právny text prevádzkovateľa.</p><p><a href="#/">Späť na domovskú stránku</a></p></article>`}
function notFound(){main.innerHTML=`<section class="section empty"><h1>Stránka sa nenašla</h1><p>Skúste vyhľadávanie alebo sa vráťte do katalógu.</p><a href="#/">Prejsť na domovskú stránku</a></section>`}
function add(id){const p=products.find(x=>x.id===id);if(!p?.stock)return;const row=state.cart.find(x=>x.id===id);row?row.qty++:state.cart.push({id,qty:1});save();showToast(`${p.name} bol pridaný do košíka`)}
function renderCartCount(){document.querySelector('#cart-count').textContent=state.cart.reduce((n,x)=>n+x.qty,0)}
function renderCart(){const rows=state.cart.map(x=>({...x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p),total=rows.reduce((n,x)=>n+x.p.price*x.qty,0);document.querySelector('#cart-content').innerHTML=rows.length?`${rows.map(x=>`<div class="cart-row"><div><strong>${esc(x.p.name)}</strong><br>${x.qty} × ${money(x.p.price)}</div><button data-remove="${x.id}" type="button">Odstrániť</button></div>`).join('')}<div class="cart-total"><span>Spolu</span><span>${money(total)}</span></div><button id="checkout-start" class="primary" type="button">Pokračovať k doprave a platbe</button>`:`<div class="empty"><h3>Váš nákupný košík je prázdny</h3><p>Vyhľadajte produkt alebo si pozrite odporúčané diely.</p><a href="#/">Prejsť na produkty</a></div>`;document.querySelector('#checkout-start')?.addEventListener('click',checkout)}
function checkout(){document.querySelector('#cart-content').innerHTML=`<form id="checkout" class="checkout"><h3>Doprava a platba</h3><label>Doprava<select name="shipping"><option>Packeta Pickup – 3,90 €</option><option>Kuriér – 5,90 €</option><option>Osobný odber Dolný Kubín – zdarma</option></select></label><label>Platba<select name="payment"><option>Bankový prevod</option><option>Platobná karta</option><option>Dobierka</option></select></label><h3>Kontaktné údaje</h3><label>Meno a priezvisko<input name="name" required autocomplete="name"></label><label>E-mail<input name="email" type="email" required autocomplete="email"></label><button class="primary" type="submit">Vytvoriť testovaciu objednávku</button></form>`;document.querySelector('#checkout').onsubmit=e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;state.cart=[];save();document.querySelector('#cart-content').innerHTML='<div class="empty"><h3>Objednávka bola prijatá</h3><p>Toto je testovacia objednávka. Žiadna platba ani e-mail neboli odoslané.</p></div>'}}
function openCart(open=true){const cart=document.querySelector('#cart'),backdrop=document.querySelector('#backdrop');cart.hidden=!open;backdrop.hidden=!open;document.querySelector('#cart-button').setAttribute('aria-expanded',String(open));if(open){renderCart();document.querySelector('#cart-close').focus()}else document.querySelector('#cart-button').focus()}
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function route(){const raw=location.hash.slice(1)||'/',[path,query='']=raw.split('?'),params=new URLSearchParams(query);state.query=params.get('q')||'';state.brand=params.get('brand')||'';if(path==='/')home();else if(path==='/search')listing({title:state.vehicle?.brand?'Kompatibilné diely':'Výsledky vyhľadávania'});else if(path.startsWith('/category/'))listing({title:'Kategória: '+path.split('/').pop(),category:path.split('/').pop()});else if(path.startsWith('/product/'))detail(path.split('/').pop());else if(path==='/sale')listing({title:'Výpredaj',sale:true});else if(path==='/brands')brands();else if(path==='/how-to')howTo();else if(path==='/terms')legal('terms');else if(path==='/privacy')legal('privacy');else notFound();document.querySelector('#search-input').value=state.query;main.focus();scrollTo(0,0)}
document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();const q=document.querySelector('#search-input').value.trim();if(!q){showToast('Zadajte názov alebo kód produktu');return}location.hash='#/search?q='+encodeURIComponent(q)};
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]'),remove=e.target.closest('[data-remove]');if(addBtn)add(addBtn.dataset.add);if(remove){state.cart=state.cart.filter(x=>x.id!==remove.dataset.remove);save();renderCart()}});
document.querySelector('#cart-button').onclick=()=>openCart(true);document.querySelector('#cart-close').onclick=()=>openCart(false);document.querySelector('#backdrop').onclick=()=>openCart(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('#cart').hidden)openCart(false)});addEventListener('hashchange',route);renderCartCount();route();
